// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtester.h for the primary calling header

#ifndef VERILATED_VTESTER___024ROOT_H_
#define VERILATED_VTESTER___024ROOT_H_  // guard

#include "verilated.h"


class Vtester__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtester___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__alu2__DOT__lc;
        VL_IN8(reset,0,0);
        VL_OUT8(finished,0,0);
        VL_OUT8(fpuen,4,0);
        CData/*4:0*/ tester__DOT__t__DOT__dinDstrobe;
        CData/*4:0*/ tester__DOT__t__DOT__doutDstrobe;
        CData/*0:0*/ tester__DOT__t__DOT__enD;
        CData/*0:0*/ tester__DOT__t__DOT__weD;
        CData/*0:0*/ tester__DOT__t__DOT__dreadyD;
        CData/*0:0*/ tester__DOT__t__DOT__accR;
        CData/*0:0*/ tester__DOT__t__DOT__flushed;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__enB;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__readyA;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__enI;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__readyI;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__enC;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__weC;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dreadyC;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__acceptingC;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__flush_l2;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__il1__DOT__hit;
        CData/*2:0*/ tester__DOT__t__DOT__s0__DOT__il1__DOT__roffset;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__il1__DOT__bl1_hit;
        CData/*3:0*/ tester__DOT__t__DOT__s0__DOT__il1__DOT__bl1_nru_bit;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__il1__DOT__zero_found;
        CData/*1:0*/ tester__DOT__t__DOT__s0__DOT__il1__DOT__candidate;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__il1__DOT__in_M_or_F;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__il1__DOT__pending;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__wvalid;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__access;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__waiting;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__waiting_en;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__flushing;
        CData/*7:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__writethrough_block;
        CData/*1:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__writethrough_way;
        CData/*4:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__set;
        CData/*4:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__set_real;
        CData/*3:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__we_local;
        CData/*4:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__baddr;
        CData/*4:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__bset;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__hit;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__miss;
        CData/*1:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__candidate;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__zero_found;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__we_pending;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__en_pending;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__writeback;
        CData/*4:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__last_set;
        CData/*2:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__roffset;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__ready;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__load_from_prev_lev;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__read_once;
        CData/*1:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__hit_way;
        CData/*1:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__miss_way;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__hitw;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__full_line_write_miss;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__srrip;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__en;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__we;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__accepting;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__pending;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__pendingI;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__IorD;
    };
    struct {
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__sen;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__swe;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__wvalid;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__access;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__flushing;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__waiting;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__waiting_en;
        CData/*7:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__writethrough_block;
        CData/*4:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__writethrough_set;
        CData/*1:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__writethrough_way;
        CData/*4:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__read_strobe;
        CData/*4:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__write_strobe;
        CData/*4:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__set_real;
        CData/*3:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__we_local;
        CData/*4:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__baddr;
        CData/*4:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__bset;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__hit;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__miss;
        CData/*1:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__candidate;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__zero_found;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__we_pending;
        CData/*1:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__we_pending_v;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__en_pending;
        CData/*1:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__en_pending_write;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__writeback;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__roffset;
        CData/*4:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__waiting_en_strobe;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__ready;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__load_from_prev_lev;
        CData/*1:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__hit_way;
        CData/*1:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__miss_way;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__hitw;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__from_writeback;
        CData/*1:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__flush_way;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__hitw_saved;
        CData/*2:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__a;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT____VdfgTmp_hc4585151__0;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__sys_inst;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__already_trapped;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__mret;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__halt;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__timer_interrupt;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__ecall_int;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__alui_enable;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__auipc_enable;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__load_enable;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__absolute_pc;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__m_inst;
        CData/*2:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__iformat;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__simd_inst;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c3_en;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__float;
        CData/*2:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__fma;
        CData/*3:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__alu_func;
        CData/*4:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__m_rd;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__m_ready;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__m_acc;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT____Vcellinp__alu2____pinNumber3;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__aluf_external;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__aluf_rd_to_vregs;
        CData/*1:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__read_rq_i_in;
        CData/*1:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__read_rq_i_out;
        CData/*4:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__rd_filter;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_not_accepting;
    };
    struct {
        CData/*5:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__fpu_valid_sr;
        CData/*5:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__fpu_rd_head;
        CData/*2:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__fpu_ffunc_head;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__fpu_ready;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_out;
        CData/*4:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_out_rd;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_out_sv;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT____Vcellinp__c1_merg____pinNumber6;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT____Vcellinp__c2_s____pinNumber4;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__to_mmap_reg;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__mmap_pend;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT____VdfgTmp_h01a245f1__0;
        CData/*6:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT____VdfgTmp_h8b5f2239__0;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__alu1__DOT__sign_swap;
        CData/*1:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__alu2__DOT__clk2;
        CData/*2:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__alu2__DOT__pend_f;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__alu2__DOT__pend;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__alu2__DOT__pend2;
        CData/*4:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT__valid_sr;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT__direction;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT__started;
        CData/*3:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT__valid_sr;
        CData/*0:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT__zero_sum;
        CData/*4:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c3__DOT__valid_sr;
        CData/*4:0*/ tester__DOT__t__DOT__md__DOT__lat;
        CData/*4:0*/ tester__DOT__t__DOT__md__DOT__send_strobe;
        CData/*7:0*/ tester__DOT__t__DOT__md__DOT__value;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tester__DOT__t__DOT__s0__DOT__c0__DOT__alu2__DOT__lc__0;
        CData/*0:0*/ __VactContinue;
        SData/*12:0*/ tester__DOT__t__DOT__s0__DOT__il1__DOT__opcode_plus;
        SData/*9:0*/ tester__DOT__t__DOT__s0__DOT__il1__DOT__bl1_delay;
        SData/*9:0*/ tester__DOT__t__DOT__s0__DOT__il1__DOT__bl1_delay_hits;
        SData/*13:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__wtag;
        SData/*13:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__wtag_next;
        SData/*13:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__tag_real;
        SData/*9:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__subset;
        SData/*14:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT__vrd1_sr;
        SData/*14:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT__vrd2_sr;
        SData/*11:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT__vrd_sr;
        SData/*14:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c3__DOT__vrd1_sr;
        SData/*14:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c3__DOT__vrd2_sr;
        SData/*9:0*/ tester__DOT__t__DOT__md__DOT__latw;
        VL_OUT(fpu1in,31,0);
        VL_OUT(fpu2in,31,0);
        VL_IN(fpuout,31,0);
        IData/*29:0*/ tester__DOT__t__DOT__addrD;
        VlWide<16>/*511:0*/ tester__DOT__t__DOT__doutD;
        IData/*31:0*/ tester__DOT__t__DOT__debug;
        IData/*20:0*/ tester__DOT__t__DOT__PCprevt;
        IData/*20:0*/ tester__DOT__t__DOT__PCprev;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__doutA;
        IData/*29:0*/ tester__DOT__t__DOT__s0__DOT__addrB;
        VlWide<8>/*255:0*/ tester__DOT__t__DOT__s0__DOT__dinB;
        VlWide<8>/*255:0*/ tester__DOT__t__DOT__s0__DOT__doutB;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__weB;
        IData/*20:0*/ tester__DOT__t__DOT__s0__DOT__addrI;
        IData/*29:0*/ tester__DOT__t__DOT__s0__DOT__addrC;
        VlWide<8>/*255:0*/ tester__DOT__t__DOT__s0__DOT__doutC;
        VlWide<8>/*255:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__wdata;
        IData/*19:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__wtag;
        IData/*19:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__wtag_next;
    };
    struct {
        IData/*19:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__tag_real;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__j_;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__we_pending_v;
        VlWide<8>/*255:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__we_pending_data;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__en_pending_write;
        IData/*29:0*/ tester__DOT__t__DOT__s0__DOT__dc1__DOT__en_pending_addr;
        IData/*29:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__addr;
        VlWide<8>/*255:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__din;
        VlWide<8>/*255:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dout;
        IData/*29:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__saddr;
        VlWide<16>/*511:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__wdata;
        VlWide<8>/*255:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__we_pending_data;
        IData/*29:0*/ tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__en_pending_addr;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__immediate;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__mstatus;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__mie;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__mtvec;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__mepc;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__mcause;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__fcsr;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__csr_value;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__csr_value_w;
        IData/*20:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__PC;
        IData/*20:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__PCnext;
        IData/*20:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__PCnext_unint;
        IData/*20:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__next_step;
        IData/*29:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__daddr;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__alu_dst;
        IData/*20:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__auipc;
        IData/*20:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__pc4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__alu_rs1;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__alu_rs2;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__m_res;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__aluf_dst;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__aluf_rs1;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__aluf_rs2;
        IData/*17:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__fpu_fma_func_sr;
        VlWide<8>/*255:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c_inA;
        VlWide<8>/*255:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c_inB;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm0____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm0____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm1____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm1____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm2____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm2____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm3____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm3____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm4____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm4____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm5____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm5____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm6____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm6____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm7____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm7____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__smodule8____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__smodule9____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__smodule10____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__smodule11____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm12____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm12____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm13____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm13____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm14____pinNumber5;
    };
    struct {
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm14____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm15____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm15____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__smodule16____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__smodule17____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__smodule18____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__smodule19____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__smodule20____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__smodule21____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm22____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm22____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm23____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm23____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm24____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm24____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm25____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm25____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm26____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm26____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm27____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm27____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__smodule28____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__smodule29____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__smodule30____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm31____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm31____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm32____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm32____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm33____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm33____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm34____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm34____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm35____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm35____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm36____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm36____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm37____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__casm37____pinNumber4;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT____Vcellout__smodule38____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm0____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm1____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm2____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm3____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm4____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm5____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm6____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm7____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm8____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm9____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm10____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm11____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm12____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm13____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm14____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm15____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm16____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm17____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm18____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm19____pinNumber3;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm20____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm21____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm22____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm23____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm24____pinNumber6;
    };
    struct {
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellinp__addm24____pinNumber5;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm25____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm26____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm27____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm28____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm29____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm30____pinNumber6;
        IData/*31:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c2_s__DOT____Vcellout__addm31____pinNumber6;
        IData/*24:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__c3__DOT__rd_sr;
        VlWide<512>/*16383:0*/ tester__DOT__t__DOT__md__DOT__rdata;
        VlWide<512>/*16383:0*/ tester__DOT__t__DOT__md__DOT__word;
        IData/*31:0*/ __VactIterCount;
        QData/*47:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__cycle_counter;
        QData/*47:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__instr_counter;
        QData/*63:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__mtimecmp;
        QData/*63:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__reg_pend;
        QData/*35:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__fpu_rd_sr;
        QData/*32:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__alu0__DOT__sub;
        QData/*63:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__alu2__DOT__num1;
        QData/*63:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__alu2__DOT__num2;
        QData/*63:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__alu2__DOT__data1s;
        QData/*63:0*/ tester__DOT__t__DOT__s0__DOT__c0__DOT__alu2__DOT__data2s;
        VlUnpacked<VlWide<8>/*255:0*/, 64> tester__DOT__t__DOT__s0__DOT__il1__DOT__mem;
        VlUnpacked<SData/*9:0*/, 64> tester__DOT__t__DOT__s0__DOT__il1__DOT__tag_array;
        VlUnpacked<CData/*0:0*/, 64> tester__DOT__t__DOT__s0__DOT__il1__DOT__valid;
        VlUnpacked<SData/*12:0*/, 4> tester__DOT__t__DOT__s0__DOT__il1__DOT__bl1_tag_array;
        VlUnpacked<CData/*0:0*/, 4> tester__DOT__t__DOT__s0__DOT__il1__DOT__bl1_valid;
        VlUnpacked<VlUnpacked<VlWide<8>/*255:0*/, 32>, 4> tester__DOT__t__DOT__s0__DOT__dc1__DOT__way;
        VlUnpacked<VlWide<8>/*255:0*/, 4> tester__DOT__t__DOT__s0__DOT__dc1__DOT__rdata;
        VlUnpacked<VlUnpacked<IData/*19:0*/, 4>, 32> tester__DOT__t__DOT__s0__DOT__dc1__DOT__tag_array;
        VlUnpacked<CData/*3:0*/, 32> tester__DOT__t__DOT__s0__DOT__dc1__DOT__dirty;
        VlUnpacked<CData/*3:0*/, 32> tester__DOT__t__DOT__s0__DOT__dc1__DOT__valid;
        VlUnpacked<VlUnpacked<CData/*1:0*/, 4>, 32> tester__DOT__t__DOT__s0__DOT__dc1__DOT__srrip_state;
        VlUnpacked<VlUnpacked<VlWide<16>/*511:0*/, 1024>, 4> tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__way;
        VlUnpacked<VlWide<16>/*511:0*/, 4> tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__rdata;
        VlUnpacked<VlUnpacked<SData/*13:0*/, 4>, 32> tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__tag_array;
        VlUnpacked<CData/*3:0*/, 32> tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__dirty;
        VlUnpacked<CData/*3:0*/, 32> tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__valid;
        VlUnpacked<VlUnpacked<CData/*1:0*/, 4>, 32> tester__DOT__t__DOT__s0__DOT__dc2__DOT__dl2u__DOT__lru_state;
        VlUnpacked<IData/*31:0*/, 64> tester__DOT__t__DOT__s0__DOT__c0__DOT__reg_file;
        VlUnpacked<CData/*4:0*/, 4> tester__DOT__t__DOT__s0__DOT__c0__DOT__read_rq_filter;
        VlUnpacked<CData/*6:0*/, 4> tester__DOT__t__DOT__s0__DOT__c0__DOT__read_rq_reg;
        VlUnpacked<VlWide<8>/*255:0*/, 4> tester__DOT__t__DOT__s0__DOT__c0__DOT__reg_file_v;
        VlUnpacked<CData/*0:0*/, 4> tester__DOT__t__DOT__s0__DOT__c0__DOT__reg_pend_v;
        VlUnpacked<IData/*31:0*/, 80> tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT__network;
        VlUnpacked<IData/*31:0*/, 8> tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT__first_half;
        VlUnpacked<IData/*31:0*/, 8> tester__DOT__t__DOT__s0__DOT__c0__DOT__c1_merg__DOT__second_half;
        VlUnpacked<VlWide<512>/*16383:0*/, 131072> tester__DOT__t__DOT__md__DOT__block_ram;
        VlUnpacked<VlWide<16>/*511:0*/, 32> tester__DOT__t__DOT__md__DOT__subblock;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtester__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtester___024root(Vtester__Syms* symsp, const char* v__name);
    ~Vtester___024root();
    VL_UNCOPYABLE(Vtester___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
